WebBanHang/Controllers/QLSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Web.Configuration;
using MyConnect;
using PetaPoco;
using System.IO;

namespace WebBanHang.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QLSanPhamController : Controller
    {
        //
        // GET: /QLSanPham/
        public ActionResult Index()
        {
            var db = MyConnectDB.GetInstance().Query<CHI_TIET>("select * from CHI_TIET");
            return View(db);
        }
        public ActionResult BAN_NHIEU()
        {

            var dl = MyConnectDB.GetInstance().Page<CHI_TIET>(1, 10, "select * from CHI_TIET order by CHI_TIET.LUOT_MUA DESC");
            return View(dl);
        }

        //
        // GET: /QLSanPham/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /QLSanPham/Create
        public ActionResult Create()
        {
            return View();
        }

        // json uoload
        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase File)
        {
            if (File != null)
            {
                if (File.ContentLength != 0)
                {
                    string path = Server.MapPath("~") + "Images";
                    string file = Request.Files[0].FileName;
                    Request.Files[0].SaveAs(path + "\\" + file);
                    Session["filename"] = file;
                    File.SaveAs(path + file);
                }
            }
             return RedirectToAction("Create");
           

        }
        // POST: /QLSanPham/Create
        [HttpPost]
        public ActionResult Create(CHI_TIET chitiet)
        {
            try
            {
                // TODO: Add insert logic here
                chitiet.HINH = (string)Session["filename"];
                MyConnectDB.GetInstance().Insert(chitiet);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /QLSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            var dl = MyConnectDB.GetInstance().Single<CHI_TIET>(id);
            return View(dl);
        }

        //
        // POST: /QLSanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CHI_TIET chitiet)
        {
            try
            {
                if (Session["filename"] != null)
                {
                    chitiet.HINH = chitiet.HINH = (string)Session["filename"];
                }
                    MyConnectDB.GetInstance().Update(chitiet);
                    return RedirectToAction("Index");
                
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /QLSanPham/Delete/5
        public ActionResult Delete(int id)
        {
            MyConnectDB.GetInstance().Delete<CHI_TIET>(id);
             return RedirectToAction("Index");
            
        }

        //
        // POST: /QLSanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, CHI_TIET sd)
        {
            try
            {

               // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            
            catch
            {
                return View();
            }
        }
    }
}

WebBanHang/Views/QLSanPham/BAN_NHIEU.cshtml
@model PetaPoco.Page<MyConnect.CHI_TIET>

@{
    ViewBag.Title = "BAN_NHIEU";
}


<div class="main_bg">
    <div class="wrap">
        <div class="main">
            <h2 class="style top">SẢN PHẨM</h2>
            <!-- start grids_of_3 -->
            <div class="grids_of_3">
                <div class="grid1_of_3">
                    @foreach (var item in Model.Items)
                    {
				    <div class="img-view">
					    <div class="img-view-bg">
                            <img src="/images/@Html.DisplayFor(modelItem => item.HINH)" alt=""/>
                        </div>
					    <h3>@Html.DisplayFor(modelItem => item.TEN_SP)</h3>
					    <div class="price">
						    <h4>$@Html.DisplayFor(modelItem => item.GIA)<span>LƯỢT BÁN: @Html.DisplayFor(modelItem => item.LUOT_MUA) </span></h4>
					    </div>
					    <span class="b_btm"></span>
		            </div>
                    }
                </div>

                <div class="clear"></div>
            </div>
            <!-- end grids_of_3 -->
        
            <div class="clear"></div>
        </div>
    </div>
</div>

WebBanHang/Views/QLSanPham/Create.cshtml
@model MyConnect.CHI_TIET

@{
    ViewBag.Title = "Create";
}


<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CHI_TIET</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.HINH, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ActionLink("Upload", "UpLoad")

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MA_SP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MA_SP)
                @Html.ValidationMessageFor(model => model.MA_SP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MA_LOAI, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MA_LOAI)
                @Html.ValidationMessageFor(model => model.MA_LOAI)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GIA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIA)
                @Html.ValidationMessageFor(model => model.GIA)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LUOT_XEM, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LUOT_XEM)
                @Html.ValidationMessageFor(model => model.LUOT_XEM)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TEN_SP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEN_SP)
                @Html.ValidationMessageFor(model => model.TEN_SP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LUOT_MUA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LUOT_MUA)
                @Html.ValidationMessageFor(model => model.LUOT_MUA)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MO_TA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MO_TA)
                @Html.ValidationMessageFor(model => model.MO_TA)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebBanHang/Views/QLSanPham/Edit.cshtml
@model MyConnect.CHI_TIET

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CHI_TIET</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div>
        <div class="form-group">
                @Html.LabelFor(model => model.HINH, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.ActionLink("Upload", "UpLoad")

                </div>
            </div>
            @Html.LabelFor(model => model.MA_SP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MA_SP)
                @Html.ValidationMessageFor(model => model.MA_SP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MA_LOAI, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MA_LOAI)
                @Html.ValidationMessageFor(model => model.MA_LOAI)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GIA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GIA)
                @Html.ValidationMessageFor(model => model.GIA)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LUOT_XEM, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LUOT_XEM)
                @Html.ValidationMessageFor(model => model.LUOT_XEM)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TEN_SP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TEN_SP)
                @Html.ValidationMessageFor(model => model.TEN_SP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LUOT_MUA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LUOT_MUA)
                @Html.ValidationMessageFor(model => model.LUOT_MUA)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MO_TA, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MO_TA)
                @Html.ValidationMessageFor(model => model.MO_TA)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebBanHang/Views/QLSanPham/Index.cshtml
@model IEnumerable<MyConnect.CHI_TIET>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="bang">
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.MA_SP)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.MA_LOAI)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.GIA)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.LUOT_XEM)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.TEN_SP)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.LUOT_MUA)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.HINH)
        </td>
        <td>
            @Html.DisplayNameFor(model => model.MO_TA)
        </td>
        <td></td>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MA_SP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MA_LOAI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GIA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LUOT_XEM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TEN_SP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LUOT_MUA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HINH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MO_TA)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {id=item.MA_SP}) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MA_SP })
        </td>
    </tr>
}

</table>

WebBanHang/Views/QLSanPham/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>
@using (Html.BeginForm("Upload", "QLSanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <input type="file" name="File" id="File"/>
    <input type="submit" name="Submit" id="Submit" value="Upload" />
}