WebBanHang/Controllers/BAI_VIETController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Web.Configuration;
using MyConnect;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System.Threading.Tasks;
using PetaPoco;


namespace WebBanHang.Controllers
{
    public class BAI_VIETController : Controller
    {
        //
        // GET: /BAI_VIET/

        public ActionResult Index()
        {
            var dl = MyConnectDB.GetInstance().Query<BAI_VIET>("select * from BAI_VIET");
            return View(dl);
        }

        //
        // GET: /BAI_VIET/Details/5

        public ActionResult Details(int? page)
        {
            int id = (int)Session["tepm"];

            if (page == null)
                page = 1;
            Page<BAI_VIET> dl = MyConnectDB.GetInstance().Page<BAI_VIET>(page.Value, 10, "select * from BAI_VIET where BAI_VIET.MA_SP=@0 order by BAI_VIET.THOI_GIAN DESC", id);
            Session["MA"] = id;
            return PartialView("Details",dl);
        }

        //
        // GET: /BAI_VIET/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /BAI_VIET/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(BAI_VIET baiviet)
        {
            try
            {
                baiviet.TAC_GIA = User.Identity.GetUserName();
                baiviet.THOI_GIAN = DateTime.Now;
                baiviet.MA_SP = (int)Session["MA"];
                MyConnectDB.GetInstance().Insert(baiviet);

                return PartialView();
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }

        }
        //
        // GET: /BAI_VIET/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /BAI_VIET/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /BAI_VIET/Delete/5
         [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            MyConnectDB.GetInstance().Delete<BAI_VIET>(id);
            return RedirectToAction("Index");
        }

        //
        // POST: /BAI_VIET/Delete/5

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

WebBanHang/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;
using System.Data.SqlClient;
using System.Web.Configuration;
using MyConnect;
using PetaPoco;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System.Threading.Tasks;


namespace WebBanHang.Controllers
{
    public class CartController : Controller
    {
        //
        // GET: /Cart/
        [Authorize]
        public ActionResult Index()
        {
            string ng = User.Identity.GetUserName();
            var dl = MyConnectDB.GetInstance().Query<MyConnect.Cart>("select * from Cart where Cart.NguoiMua =@0",ng);
            return View(dl);
        }

        //
        
        //addcart
        public ActionResult AddCart(int id)
        {
            var temp = User.Identity.GetUserName();
            var nd = MyConnectDB.GetInstance().Query<NGUOI_DUNG>("select * from NGUOI_DUNG where NGUOI_DUNG.TEN_DN = @0",temp).FirstOrDefault();
            var db = MyConnectDB.GetInstance().Single<MyConnect.CHI_TIET>(id);
            var dulieu = new WebBanHang.Models.Cart();
            Session["SanPham"] = db.TEN_SP;
            Session["Gia"] = db.GIA;
            dulieu.NguoiMua = "null";
            dulieu.ID = 0;
            dulieu.SanPham = db.TEN_SP;
            dulieu.Tien = db.GIA;
            dulieu.SoLuong = 1;
            return View(dulieu);
        }
        // GET: /Cart/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Cart/Create
        public ActionResult Create()
        {
            return View();
        }

        //
     
        // POST: /Cart/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(MyConnect.Cart cart)
        {
            try
            {
                string ng = User.Identity.GetUserName();
                var nd = MyConnectDB.GetInstance().Query<NGUOI_DUNG>("select * from NGUOI_DUNG where NGUOI_DUNG.TEN_DN = @0", ng).FirstOrDefault();
                
                int mn = (int)Session["Gia"];
                cart.SDT = nd.SDT;
                cart.NGAY = DateTime.Now;
                cart.DIA_CHI = nd.DIA_CHI;
                cart.NguoiMua = ng;
                cart.Tien = cart.SoLuong * mn;
                cart.SanPham = (string)Session["SanPham"];
                MyConnectDB.GetInstance().Insert(cart);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Cart/Edit/5
        [HttpPost]
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Cart/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Cart/Delete/5
        public ActionResult Delete(int id)
        {
            var dl=MyConnectDB.GetInstance().Single<MyConnect.Cart>(id);
            return View(dl);
        }

        //
        // POST: /Cart/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, MyConnect.Cart nd)
        {
            try
            {
                // TODO: Add delete logic here
                var result = MyConnectDB.GetInstance().Delete(nd);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

WebBanHang/Controllers/SAN_PHAMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Web.Configuration;
using MyConnect;
using PetaPoco;

namespace WebBanHang.Controllers
{
    public class SAN_PHAMController : Controller
    {
        //
        // GET: /Default1/
        public ActionResult Index(int? page)
         {
            if (page == null)
                page = 1;
            Page<CHI_TIET> dl = MyConnectDB.GetInstance().Page<CHI_TIET>(page.Value,6, "select * from CHI_TIET");
            return PartialView(dl);
        }
        //6 san ham ban chay
        // 6 san xem nhieu
        public ActionResult XEM_NHIEU(int id)
        {
            var dl = MyConnectDB.GetInstance().Page<CHI_TIET>(1, 6, "select * from CHI_TIET order by CHI_TIET.LUOT_XEM DESC");
            return View(dl);
        }
        // 3 san pham lien quan
        public ActionResult LIEN_QUAN(int id)
        {
            var db = MyConnectDB.GetInstance().Single<CHI_TIET>(id);
            var dl = MyConnectDB.GetInstance().Page<CHI_TIET>(1, 3, "SELECT * FROM CHI_TIET WHERE CHI_TIET.MA_LOAI=@0 ", db.MA_LOAI);
            return View(dl);
        } 
      

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id)
        {
            Session["tepm"] = id;
            var dl = MyConnectDB.GetInstance().Single<CHI_TIET>(id);
            dl.LUOT_XEM = dl.LUOT_XEM + 1;
            MyConnectDB.GetInstance().Update("CHI_TIET", "MA_SP",dl);
            var db = MyConnectDB.GetInstance().Single<CHI_TIET>(id);
            return View(db);
        }
        [HttpPost]
        public ActionResult PatialCreate(BAI_VIET baiviet)
        {
            try
            {
                baiviet.THOI_GIAN = DateTime.Now;

                MyConnectDB.GetInstance().Insert(baiviet);

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }


        // danh sach loai san pham
        public ActionResult LoaiSP(int id)
        {
           var dl = MyConnectDB.GetInstance().Query<LOAI>("select * from LOAI ");
            return View(dl);
        }
        //sản phẩm theo loại
        public ActionResult XemLOAI(int id)
        {
            var dl = MyConnectDB.GetInstance().Query<CHI_TIET>("select * from CHI_TIET where CHI_TIET.MA_LOAI=@0", id);
            return View(dl);
        }
        // GET: /Default1/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /BAI_VIET/Create

        //
        // GET: /Default1/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Default1/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebBanHang/Views/SAN_PHAM/Details.cshtml
@model MyConnect.CHI_TIET
@{
    ViewBag.Title = "Details";
}

<div class="main_bg">
<div class="wrap" style="width:90%;margin-left:5%;">	
	<div class="main">
	<!-- start content -->
	<div class="single">
			<!-- start span1_of_1 -->
			<div class="left_content">
			<div class="span1_of_1">
				<!-- start product_slider -->
				<div class="product-view">				     
                    <img src="/images/@Html.DisplayFor(model => model.HINH)" alt="Women Shorts" title="Women Shorts" />
				</div>
				<!-- end product_slider -->
			</div>
			<!-- start span1_of_1 -->
			<div class="span1_of_1_des">
                    <div class="desc1">
                        <h3>
                            @Html.DisplayFor(model => model.TEN_SP)
                        </h3>
                        <h3>
                            LƯỢT XEM: @Html.DisplayFor(model => model.LUOT_XEM)
                        </h3>
                        <h5>
                            GIÁ: $ @Html.DisplayFor(model => model.GIA)
                        </h5>
                        <div class="available">
                            <h4>MÔ TẢ : @Html.DisplayFor(model => model.MO_TA)</h4>
                          
                        </div>
                        <div class="btn_form">
                            <form action="@Url.Action("AddCart", "Cart", new{id = Model.MA_SP})">
                                <input type="submit" value="add to cart" title="" />
                            </form>
                        </div>
                   
                         
                                <div class="clear"></div>
 </div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
    
				</div>	<!-- end sidebar -->
          	    <div class="clear"></div>
	       </div>	
	<!-- end content -->
        <div class="clear"></div>
	</div>
 
         @Html.Action("LIEN_QUAN", "SAN_PHAM", new {id = Model.MA_LOAI})
        <div class="clear"></div>
        <div>@Html.Action("Details", "BAI_VIET") </div>
        <div>@Html.Action("Create", "BAI_VIET") </div>
        

       
</div>
</div>

@section Scripts {

    <script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
}

WebBanHang/Views/SAN_PHAM/Index.cshtml
@model PetaPoco.Page<MyConnect.CHI_TIET>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Main.cshtml";
}


<div class="main_bg">
    <div class="wrap">
        <div class="main">
            <h2 class="style top">SẢN PHẨM</h2>
            <p style="text-align:center;">
                @for (int i = 1; i <= Model.TotalPages; i++)
                {


                    <a href="/SAN_PHAM?page=@i" style="color:#777">@i</a>
                }
            </p>
            <!-- start grids_of_3 -->
            <div class="grids_of_3">
                <div class="grid1_of_3">
                    @foreach (var item in Model.Items)
                    {
                        <div class="img-view">
                            <div class="img-view-bg">
                                <img src="/images/@Html.DisplayFor(modelItem => item.HINH)" alt="" />
                            </div>
                            <h3>@Html.DisplayFor(modelItem => item.TEN_SP)</h3>
                            <div class="price">
                                <h4>$@Html.DisplayFor(modelItem => item.GIA)<span>@Html.ActionLink("Details", "Details", new { id = item.MA_SP })</span></h4>
                            </div>
                            <span class="b_btm"></span>
                        </div>
                    }
                </div>

                <div class="clear"></div>
            </div>
            <!-- end grids_of_3 -->
            @Html.Action("XEM_NHIEU", "SAN_PHAM", new { id = 0 })
            @Html.Action("LoaiSP", "SAN_PHAM", new { id = 0 })
            <div class="clear"></div>
        </div>
    </div>
</div>

WebBanHang/Views/SAN_PHAM/LIEN_QUAN.cshtml
@model PetaPoco.Page < MyConnect.CHI_TIET >
@{
    Layout = null;
  }
	<h2 class="style top">SẢN PHẨM CÙNG LOẠI</h2>

		<!-- start grids_of_3 -->
		<div class="grids_of_3">
			<div class="grid1_of_3">
                @foreach(var item in Model.Items)
                {
				    <div class="img-view">
					    <div class="img-view-bg">
                            <img src="/images/@Html.DisplayFor(modelItem => item.HINH)" alt=""/>
                        </div>
					    <h3>@Html.DisplayFor(modelItem => item.TEN_SP)</h3>
					    <div class="price">
						    <h4>$@Html.DisplayFor(modelItem => item.GIA)<span>@Html.ActionLink("Details", "Details", new { id = item.MA_SP })</span></h4>
					    </div>
					    <span class="b_btm"></span>
		            </div>
                }
              </div>

			<div class="clear"></div>
		</div>

WebBanHang/Views/SAN_PHAM/LoaiSP.cshtml
@model IEnumerable<MyConnect.LOAI>

@{
    Layout = null;
 }
<div class="left_sidebar">
			<div class="sellers">
				<h4>DANH SÁCH LOẠI</h4>
				<div class="single-nav">
			        <ul>
                        @foreach (var item in Model)
                        {
                            <li><a href="@Url.Action("XemLoai", "SAN_PHAM", new {id = item.MA_LOAI })">@Html.DisplayFor(modelItem => item.TEN)</a></li>
                        }		                    
			        </ul>
			        </div>
			</div>
		</div>

WebBanHang/Views/SAN_PHAM/XEM_NHIEU.cshtml
@model PetaPoco.Page < MyConnect.CHI_TIET >
@{
    Layout = null;
  }
	<h2 class="style top" style="float:none;clear:both">XEM_NHIEU</h2>

		<!-- start grids_of_3 -->
		<div class="grids_of_3">
			<div class="grid1_of_3">
                @foreach(var item in Model.Items)
                {
				    <div class="img-view">
					    <div class="img-view-bg">
                            <img src="/images/@Html.DisplayFor(modelItem => item.HINH)" alt=""/>
                        </div>
					    <h3>@Html.DisplayFor(modelItem => item.TEN_SP)</h3>
					    <div class="price">
						    <h4>$@Html.DisplayFor(modelItem => item.GIA)<span>@Html.ActionLink("Details", "Details", new { id = item.MA_SP })</span></h4>
					    </div>
					    <span class="b_btm"></span>
		            </div>
                }
              </div>

			<div class="clear"></div>
		</div>

WebBanHang/Views/SAN_PHAM/XemLOAI.cshtml
@model IEnumerable<MyConnect.CHI_TIET>

@{
    ViewBag.Title = "XemLOAI";
}

<div class="main_bg">
<div class="wrap">	
	<div class="main">
		<h2 class="style top">DANH SÁCH</h2>
		<!-- start grids_of_3 -->
		<div class="grids_of_3">
			<div class="grid1_of_3">
                @foreach(var item in Model)
                {
				    <div class="img-view">
					    <div class="img-view-bg">
                            <img src="/images/@Html.DisplayFor(modelItem => item.HINH)" alt=""/>
                        </div>
					    <h3>@Html.DisplayFor(modelItem => item.TEN_SP)</h3>
					    <div class="price">
						    <h4>$@Html.DisplayFor(modelItem => item.GIA)<span>@Html.ActionLink("Details", "Details", new { id = item.MA_SP })</span></h4>
					    </div>
					    <span class="b_btm"></span>
		            </div>
                }
              </div>

			<div class="clear"></div>
		</div>	
		<!-- end grids_of_3 -->
        <div class="clear"></div>
	</div>
</div>
</div>	
  