WebBanHang/Controllers/DICH_VUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBanHang.Controllers
{
    public class DICH_VUController : Controller
    {
        //
        // GET: /DICH_VU/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /DICH_VU/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /DICH_VU/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /DICH_VU/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /DICH_VU/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /DICH_VU/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /DICH_VU/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /DICH_VU/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebBanHang/Controllers/SAN_PHAMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Web.Configuration;
using MyConnect;
using PetaPoco;

namespace WebBanHang.Controllers
{
    public class SAN_PHAMController : Controller
    {
        //
        // GET: /Default1/
        public ActionResult Index(int? page)
         {
            if (page == null)
                page = 1;
            Page<CHI_TIET> dl = MyConnectDB.GetInstance().Page<CHI_TIET>(page.Value,6, "select * from CHI_TIET");
            return PartialView(dl);
        }
        //6 san ham ban chay
        // 6 san xem nhieu
        public ActionResult XEM_NHIEU(int id)
        {
            var dl = MyConnectDB.GetInstance().Page<CHI_TIET>(1, 6, "select * from CHI_TIET order by CHI_TIET.LUOT_XEM DESC");
            return View(dl);
        }
        // 3 san pham lien quan
        public ActionResult LIEN_QUAN(int id)
        {
            var db = MyConnectDB.GetInstance().Single<CHI_TIET>(id);
            var dl = MyConnectDB.GetInstance().Page<CHI_TIET>(1, 3, "SELECT * FROM CHI_TIET WHERE CHI_TIET.MA_LOAI=@0 ", db.MA_LOAI);
            return View(dl);
        } 
      

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id)
        {
            Session["tepm"] = id;
            var dl = MyConnectDB.GetInstance().Single<CHI_TIET>(id);
            dl.LUOT_XEM = dl.LUOT_XEM + 1;
            MyConnectDB.GetInstance().Update("CHI_TIET", "MA_SP",dl);
            var db = MyConnectDB.GetInstance().Single<CHI_TIET>(id);
            return View(db);
        }
        [HttpPost]
        public ActionResult PatialCreate(BAI_VIET baiviet)
        {
            try
            {
                baiviet.THOI_GIAN = DateTime.Now;

                MyConnectDB.GetInstance().Insert(baiviet);

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }


        // danh sach loai san pham
        public ActionResult LoaiSP(int id)
        {
           var dl = MyConnectDB.GetInstance().Query<LOAI>("select * from LOAI ");
            return View(dl);
        }
        //sản phẩm theo loại
        public ActionResult XemLOAI(int id)
        {
            var dl = MyConnectDB.GetInstance().Query<CHI_TIET>("select * from CHI_TIET where CHI_TIET.MA_LOAI=@0", id);
            return View(dl);
        }
        // GET: /Default1/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /BAI_VIET/Create

        //
        // GET: /Default1/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Default1/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebBanHang/Controllers/THONG_TINController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBanHang.Controllers
{
    public class THONG_TINController : Controller
    {
        //
        // GET: /THONG_TIN/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /THONG_TIN/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /THONG_TIN/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /THONG_TIN/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /THONG_TIN/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /THONG_TIN/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /THONG_TIN/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /THONG_TIN/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebBanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Cart", "Index", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebBanHang/Views/Shared/_Main.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Free Aditii Website Template | Home </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <!-- start slider -->
    <link href="~/Content/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script type="text/javascript" src="~/Scripts/modernizr.custom.28468.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.cslider.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#da-slider').cslider();
        });
    </script>
    <!-- Owl Carousel Assets -->
    <link href="~/Content/owl.carousel.css" rel="stylesheet">
    <!-- Owl Carousel Assets -->
    <!-- Prettify -->
    <script src="~/Scripts/owl.carousel.js"></script>
    <script>
        $(document).ready(function () {

            $("#owl-demo").owlCarousel({
                items: 4,
                lazyLoad: true,
                autoPlay: true,
                navigation: true,
                navigationText: ["", ""],
                rewindNav: false,
                scrollPerPage: false,
                pagination: false,
                paginationNumbers: false,
            });

        });
    </script>
    <!-- //Owl Carousel Assets -->
    <!-- start top_js_button -->
    <script type="text/javascript" src="~/Scripts/move-top.js"></script>
    <script type="text/javascript" src="~/Scripts/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1200);
            });
        });
    </script>
</head>
<body>
    <!-- start header -->
    <div class="header_bg">
        <div class="wrap">
            <div class="header">
                <div class="logo">
                    <a href="index.html"><img src="images/logo.png" alt="" /> </a>
                </div>
                <div class="h_icon">
                    <ul class="icon1 sub-icon1">
                        <li>
                            <a class="active-icon c1" href="@Url.Action("Index","Cart")"></a>
                            <ul class="sub-icon1 list">
                                <li><h3>shopping cart empty</h3><a href=""></a></li>
                                <li><p>if items in your wishlit are missing, <a href="contact.html">contact us</a> to view them</p></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="h_search">
                    <form action="@Url.Action("TIM_KIEM","Home")">
                        <input type="text" value="" name="tukhoa">
                        <input type="submit" value="">
                    </form>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="header_btm">
        <div class="wrap">
            <div class="header_sub">
                <div class="h_menu">
                    <ul>
                        <li class="active">@Html.ActionLink("Trang Chủ", "Index", "Home")</li> |
                        <li class="active">@Html.ActionLink("Sản Phẩm", "Index", "SAN_PHAM")</li> |
                        <li>@Html.ActionLink("DỊCH VỤ", "Index", "DICH_VU")</li> |
                        <li>@Html.ActionLink("THÔNG TIN", "Index" , "THONG_TIN" )</li> |
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
                <div class="top-nav">
                    <nav class="nav">
                        <a href="#" id="w3-menu-trigger"> </a>
                        <ul class="nav-list" style="">
                            <li class="nav-item"><a class="active" href="index.html">Home</a></li>
                            <li class="nav-item"><a href="danhsach.html">List Sản Phẩm</a></li>
                            <li class="nav-item"><a href="service.html">Services</a></li>
                            <li class="nav-item"><a href="contact.html">Contact</a></li>
                        </ul>
                    </nav>
                    <div class="search_box">
                        <form>
                            <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
                        </form>
                    </div>
                    <div class="clear"> </div>
                    <script src="js/responsive.menu.js"></script>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!-- start slider -->
    @RenderSection("featured", required: false)
    @RenderSection("scripts", required: false)
    @RenderBody()

    <!-- start footer -->
    <div class="footer_bg1">
        <div class="wrap">
            <div class="footer">
                <!-- scroll_top_btn -->
                <script type="text/javascript">
                    $(document).ready(function () {

                        var defaults = {
                            containerID: 'toTop', // fading element id
                            containerHoverID: 'toTopHover', // fading element hover id
                            scrollSpeed: 1200,
                            easingType: 'linear'
                        };


                        $().UItoTop({ easingType: 'easeOutQuart' });

                    });
                </script>
                <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
                <!--end scroll_top_btn -->
                <div class="copy">
                    <p class="link">Copyright &copy; 2014.Company name All rights reserved.<a target="_blank" href="http://myxem.com">MYXEM</a></p>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</body>
</html>